version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Athens"
  open-pull-requests-limit: 10
  versioning-strategy: auto
